### ISSUE TITLE
how do I  help correct and clarify info in your instructions and docs?

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/generator-builder#11]
## Correction needed on the following page

http://labs.infyom.com/laravelgenerator/docs/options/scaffold-options
# change
## Datatables

Generator also have ability to generate CRUD file with datatables. To enable datatables option, you need to install yajra/laravel-datatables package. You can find a full installation steps here.

Once, you are done with installation.
Make 'add_on.datatables' => true in config/infyom/**_generator_builder.php.**_
# to this
## Datatables

Generator also have ability to generate CRUD file with datatables. To enable datatables option, you need to install yajra/laravel-datatables package. You can find a full installation steps here.

Once, you are done with installation.
Make 'add_on.datatables' => true in config/infyom/**_laravel_generator.php.**_

I  would help you with these but im not sure where to do it. 
There are some others as well. 

Also any news on the routePrefix and pathPrefix options 
and possibly a %prefix us this layout option%

**Comment by phillipmadsen** [comment]
## also I  see you added this.

``` php
        // Set the view prefix if you have sub folders in views folder.
        // If you have resources/views/backend/admin set in your path => views above
        // then value should be 'view_prefix' => 'backend.admin'
        'view_prefix' => ''
```

this Is a great idea but it will not really work for pathPrefix if that is what you are going for. 

example
let say there is a admin section and then the normal non prefixed  views.
so for - routes using **_admin.page.index**_
with - path directory **_base_path. '/backend/pages/index.blade.php'**_

if you use this  ( 'view_prefix' => 'backend.admin') 

it would generate - path directory **_base_path. '/backend/ ADMIN /pages/index.blade.php'**_ and by doing this all the links routes and everything else would be wrong and have to be redone. This would be the same problem it has now. 

### backend is admin

SO 

### backend/admin (will not work)

### does this make sense to you. if I  need to explain it better I  can just let me know.

do  you skype?

**Comment by phillipmadsen** [comment]
## Idea

### you could do something like this to make it a bit simpler

``` php
   'options' => [
        'softDelete' => true,
        'tables_searchable_default' => false,
       'path_prefix' => 'backend'
       'path_prefix_layout_theme' => 'core-templates'
    //   'path_prefix_views' => 'index,create,edit,delete,datatable' // generated using the theme layout specified above
       'route_prefix' => 'Admin'
    ],
|- views
    |- backend
         |- layouts
             |- partials
             |- includes
             |- app.blade.php // based off core-templates
         |- pages
             |- index.blade.php
             |- datatable.blade.php
             |- create.blade.php
             |- edit.blade.php
             |- delete.blade.php

```

### and these would supercede any flags if set.

This would get us half way to the right place and make it usable. 
for instance the example above would generate the admin for the model 
we could then edit these for the non admin part  such as the following

``` php
   'options' => [
        'softDelete' => true,
        'tables_searchable_default' => false,
        'path_prefix' => 'frontend'
        'path_prefix_layout_theme' => 'live-site-theme'
    //   'path_prefix_views' => 'index,show' // generated using the theme layout specified above
        'route_prefix' => ''
    ],
|- views
    |- frontend
         |- layouts
             |- partials
             |- includes
             |- app.blade.php // based off live-site-theme
         |- pages
             |- index.blade.php
             |- show.blade.php
```

**Comment by phillipmadsen** [comment]
php artisan infyom.publish:tests does not work did you change that command to php artisan infyom.api:tests?

**Comment by mitulgolakiya** [comment]
It was never `infyom.publish:tests`. It was always `infyom.api:tests`.

Also the documentation repo is currently private repo. But I am going to open source it soon.

**Comment by mitulgolakiya** [comment]
Closing this issue in reference of https://github.com/InfyOmLabs/laravel-generator/issues/155 for prefix discussion. so we can have whole discussion at single place.

**Comment by anaisorozcoapok** [comment]
Hi, mitulgolakiya 
I'm just using your laravel 5.5 project managed by infyom now how can I prove that the APIs I made are correct by mediating this generator

Thanks,
Anais
