### ISSUE TITLE
HtmlType not all types choosable

### ISSUE THREAD

**Issue by kay899** [InfyOmLabs/generator-builder#13]
Hi,

I noticed that not all existing HtmlTypes are choosable in the Builder UI.

Is there a reason why types like boolean and toogle are missing?

Regards
kay899

**Comment by farhaninfyom** [comment]
`boolean` is  DB type we can not use for HTML Type we can set HTML Type like checkbox for render `boolean` attribute. also we can use others HTML Type attribute for `toggle`.
