### ISSUE TITLE
How to build boolean field with Generator UI?

### ISSUE THREAD

**Issue by kay899** [InfyOmLabs/generator-builder#14]
Hi,

I want to build an active flag with Generator UI.

Choosing boolean as DB type and Checkbox as HtmlType.

Generation is then failing. I suppose that this fieldtype need more info then just the HtmlType name, right?

`"fieldInput": "is_active:boolean", /* BOOLEAN CHECKBOX */`

`"htmlType": "bool-checkbox:checked", /* OPTIONS ARE CHECKED | UNCHECKED */`

How could we use Checkboxes or Bools with the Generator UI?

Regards
kay899

**Comment by farhaninfyom** [comment]
you can see the steps here : https://www.useloom.com/share/5cac9967c02c454fa00a2ec59eed0435
