### ISSUE TITLE
League\Flysystem\Plugin\PluggableTrait' not found

### ISSUE THREAD

**Issue by cutemonster** [InfyOmLabs/generator-builder#15]
When I do php artisan vendor:publish
It cannot find League\Flysystem\Plugin\PluggableTrait'

I cannot find manually either.  Could you tell me how to solve this?

**Comment by vishalinfyom** [comment]
@cutemonster I think you should ask this into https://github.com/thephpleague/flysystem repo. you will get better answer from there.
