### ISSUE TITLE
issue with migration and underscore

### ISSUE THREAD

**Issue by kirchaj** [InfyOmLabs/generator-builder#17]
I have created a scaffold with the model Order_Status.  There are two issues that seem to be generated.

First, the migration is created with 
class CreateOrder_StatusesTable extends Migration but when I try to migrate I get the error 
 [Symfony\Component\Debug\Exception\FatalThrowableError]
 Class 'CreateOrderStatusesTable' not found             

If I change the line to class CreateOrderStatusesTable extends Migration     the migration runs.

In the migration file, the generator is also putting double underscores in the create and drop table name 
 Schema::drop('order__statuses');

**Comment by kirchaj** [comment]
sorry.  This really should have gone under the laravel-generator.

**Comment by mitulgolakiya** [comment]
@kirchaj try to use `OrderStatus` as model name.
