### ISSUE TITLE
Laravel 5.3 

### ISSUE THREAD

**Issue by KyberID** [InfyOmLabs/generator-builder#19]
http://take.ms/n1ChG
http://take.ms/mgnHD
http://take.ms/E3cio
?

**Comment by Alfulayt** [comment]
+1

**Comment by pckz** [comment]
+1

**Comment by farhaninfyom** [comment]
@KyberID @abdualrhmanio Version 5.3 is no longer maintained. Try to use 5.5 or later.
Here is screen shots of laravel 5.5, and its working fine, hope it does not happen again.
![issue_19_1](https://user-images.githubusercontent.com/37834439/55620595-e3dcad00-57b8-11e9-8122-b14be9adb398.png)
![issue_19_2](https://user-images.githubusercontent.com/37834439/55620615-ec34e800-57b8-11e9-9b41-6fe2d12cb3b0.png)
