### ISSUE TITLE
Generator useless on mine

### ISSUE THREAD

**Issue by qeifar** [InfyOmLabs/generator-builder#21]
I am using Laravel 5.4, The generator js work fine. I can add field and all but after i clicked GENERATE button it showed successful but nothing changed on my code. Please help me

**Comment by qeifar** [comment]
plus I am not like others, I HAVE NO ERROR WHEN RUNNING IT. It just nothing showed up

**Comment by farhaninfyom** [comment]
duplicate in context of #23, #25
