### ISSUE TITLE
 Error in generator gui interface when clicking generate

### ISSUE THREAD

**Issue by henriqueraptor** [InfyOmLabs/generator-builder#23]
I am using laravel 5.4 when trying to generate by the generator gui interface accuse Result! Fail error when clicking the generate button.
I made the installation according to the documentation.

![screen shot 07-26-17 at 03 38 pm](https://user-images.githubusercontent.com/26465681/28637665-b925146c-7218-11e7-906e-58769f47619f.PNG)

**Comment by mafudelaptu** [comment]
+1 got same  behavior

**Comment by evertonpaiva** [comment]
I'm having the same problem.

**Comment by morningmemo** [comment]
+1 got same behavior

**Comment by mzaalan** [comment]
you can try this : 
https://github.com/InfyOmLabs/generator-builder/pull/22

**Comment by morningmemo** [comment]
@mzaalan noooooo.... still not working, same error

"exception": "Symfony\\Component\\HttpKernel\\Exception\\HttpException"

**Comment by francis-santos** [comment]
+1
