### ISSUE TITLE
Fatal error: Class 'Illuminate\Support\Composer' not found

### ISSUE THREAD

**Issue by emahuni** [InfyOmLabs/generator-builder#4]
This error happens in Laravel 5.2.x when i try to create a model. It seems like the API that does the creating is not up to date. I read this about another package when I Googled:

https://github.com/laralib/l5scaffold/issues/29

That's a similar error as this one. The simplest temporary solution would be to do a recursive search of Illuminate\Foundation\Composer in your vendors directory and replace it with Illuminate\Support\Composer throughout your project...
Afterwards you'll have to wait for the needed changes being adopted by the package vendors.

When I generated using command prompt everything worked well. So I think this is isolated to the Gui Builder.

**Comment by vishalinfyom** [comment]
@emahuni Generator-builder with laravel-5.2 is no longer maintained. Try to use 5.5 or later.
