### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by phillipmadsen** [InfyOmLabs/generator-builder#5]
when you click the generate button is is supposed to run the command type command. All it is doing on mine is creating the migration file. nothing else. Am I  missing a step.

**Comment by phillipmadsen** [comment]
Is it also supposed to generate the fields-file.json for the given generation. it is also not working.

**Comment by LeifErickson** [comment]
I also have this problem

**Comment by mitulgolakiya** [comment]
I will review it and will check if I missed anything in documentation.

**Comment by onyx26** [comment]
I was having the same problem: when I checked the logs it was complaining about a Swagger template, even though I hadn't ticked the Swagger box:

exception 'ErrorException' with message 'file_get_contents(/home/onyx26/admintest/vendor/infyomlabs/swagger-generator/templates/model/model.stub): failed to open stream: No such file or directory' 

Installing Swaggervel fixed the issue and I now get a "Files created successfully" message.
