### ISSUE TITLE
i get this when i try to route to Route::get('generator_builder', '\InfyOm\GeneratorBuilder\Controllers\GeneratorBuilderController@builder');

### ISSUE THREAD

**Issue by sanamshrestha123** [InfyOmLabs/generator-builder#51]
Route [io_field_template] not defined. (View: C:\xampp\htdocs\advertisement\vendor\infyomlabs\generator-builder\views\builder.blade.php)

**Comment by ajayinfyom** [comment]
@sanamshrestha123 You should run `php artisan infyom.publish:generator-builder`

It will publish routes in routes.php with named routes.

**Comment by ajayinfyom** [comment]
Updated docs to publishing routes in generator builder.

you can check here: https://labs.infyom.com/laravelgenerator/docs/6.0/gui-interface#routes-publish-command
