### ISSUE TITLE
×Fail! Use of undefined constant STDIN 

### ISSUE THREAD

**Issue by egyleader** [InfyOmLabs/generator-builder#54]
I had this error when I tried to use the generator builder on` Laravel Framework 7.6.2`

> ×Fail! Use of undefined constant STDIN - assumed 'STDIN' (this will throw an Error in a future version of PHP)
and this was my input : 
![ScreenShot_20200418010424](https://user-images.githubusercontent.com/31688162/79620585-9ce5ff00-8110-11ea-9ec0-2f3af81573cd.png)

**Comment by tovaz** [comment]
I have same issue too
![Captura de pantalla de 2020-08-03 09-51-01](https://user-images.githubusercontent.com/11469828/89158823-ee56b480-d56e-11ea-9195-e0cc3efb0fe0.png)

**Comment by tovaz** [comment]
I fixed unchecking Save Schema , it works for me

**Comment by mitulgolakiya** [comment]
Maybe because you have not defined your PHP CLI or your CLI and web PHP versions are different.

Maybe `define('STDIN',fopen("php://stdin","r"));` can help.
